### ISSUE TITLE
set up CamelCaseToSnakeCaseNameConverter in this bundle

### ISSUE THREAD

**Issue by novotnicek** [williarin/wordpress-interop-bundle#6]
Hello William.

In first, thank you for your work on great projects like sword-bundle and wordpress-interop-bundle. It's super cool.

I think CamelCaseToSnakeCaseNameConverter will be better set up in this bundle settings, and not in higher layer (in example by rewrite my default serializer settings in my symfony application).

I make PR for this. Yes, it's more lines than current status, but i think, now it's more "independent".

Can you check this PR? What do you think about it?

Thank you a lot.

**Comment by novotnicek** [comment]
PR: https://github.com/williarin/wordpress-interop-bundle/pull/7

**Comment by williarin** [comment]
Fixed by #8
